version: 2

models:
  - name: dim_app
    columns:
      - name: app_key
        tests:
          - not_null
          - unique
      - name: app_id
        tests:
          - not_null
          - unique

  - name: dim_date
    columns:
      - name: date_key
        tests:
          - not_null
          - unique
      - name: date
        tests:
          - not_null

  - name: dim_user
    columns:
      - name: user_key
        tests:
          - not_null
          - unique
      - name: user_name
        tests:
          - not_null